eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: youhong
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
    username: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
env: sssssssss
girl:
  name: aaaaaaaa
  age: 24
